# Generated by Django 3.2.7 on 2021-09-19 15:33

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50, verbose_name='Topic of discussion')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default=django.contrib.auth.models.User, max_length=50, verbose_name='Sender`s name')),
                ('text', models.TextField(verbose_name='Text')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 9, 19, 18, 33, 41, 339060), verbose_name='Date and time')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Anon')),
                ('topic_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.topic')),
            ],
        ),
    ]
