# Generated by Django 3.2.7 on 2021-09-19 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 22, 54, 12, 127075), verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=50, verbose_name='Sender`s name'),
        ),
    ]
