# Generated by Django 3.2.7 on 2021-09-20 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210919_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 20, 21, 23, 880252), verbose_name='Date and time'),
        ),
        migrations.CreateModel(
            name='DelayedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='Sender`s name')),
                ('text', models.TextField(verbose_name='Text')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 9, 20, 20, 21, 23, 881254), verbose_name='Date and time')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Anon')),
                ('topic_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.topic')),
            ],
        ),
    ]
