# Generated by Django 3.2.7 on 2021-09-20 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210920_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delayedmessages',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 21, 24, 43, 543378), verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 21, 24, 43, 542379), verbose_name='Date and time'),
        ),
    ]
